"""nox configuration for Times Square."""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import sys
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

import nox
from nox.command import CommandFailed
from nox_uv import session

# Default sessions
nox.options.sessions = ["lint", "typing", "test", "docs"]

# Other nox defaults
nox.options.default_venv_backend = "uv"
nox.options.reuse_existing_virtualenvs = True

# A syntactically valid Gafaelfawr token for test configurations.
_TEST_GAFAELFAWR_TOKEN = "gt-eOfLolxU8FJ1xr08U7RTbg.Jr-KHSeISXwR5GXHiLemhw"


@session(uv_only_groups=["lint"], uv_no_install_project=True)
def lint(session: nox.Session) -> None:
    """Run pre-commit hooks with prek."""
    session.run("prek", "run", "--all-files", *session.posargs)


@session(uv_groups=["dev", "nox", "typing"])
def typing(session: nox.Session) -> None:
    """Run mypy."""
    session.run("mypy", "noxfile.py", "src/timessquare", "tests")


@session(uv_groups=["dev"])
def test(session: nox.Session) -> None:
    """Run pytest."""
    with _start_containers() as env_vars:
        env_vars["TS_ARQ_MODE"] = "test"
        session.run("pytest", "-vv", *session.posargs, env=env_vars)


@session(name="test-coverage", uv_groups=["dev"])
def test_coverage(session: nox.Session) -> None:
    """Run pytest with coverage reporting."""
    with _start_containers() as env_vars:
        env_vars["TS_ARQ_MODE"] = "test"
        session.run(
            "pytest",
            "-vv",
            "--cov=timessquare",
            "--cov-branch",
            "--cov-report=",
            *session.posargs,
            env=env_vars,
        )


@session(name="coverage-report", uv_groups=["dev"])
def coverage_report(session: nox.Session) -> None:
    """Generate a code coverage report from the test-coverage session."""
    session.run("coverage", "report", *session.posargs)


@session(uv_groups=["dev", "docs"])
def docs(session: nox.Session) -> None:
    """Build the documentation."""
    doctree_dir = (session.cache_dir / "doctrees").absolute()
    with session.chdir("docs"):
        session.run(
            "sphinx-build",
            "--keep-going",
            "-n",
            "-T",
            "-b",
            "html",
            "-d",
            str(doctree_dir),
            ".",
            "./_build/html",
            env=_make_env_vars({"TS_ARQ_MODE": "test"}),
        )


@session(name="docs-linkcheck", uv_groups=["dev", "docs"])
def docs_linkcheck(session: nox.Session) -> None:
    """Check links in the documentation."""
    doctree_dir = (session.cache_dir / "doctrees").absolute()
    with session.chdir("docs"):
        try:
            session.run(
                "sphinx-build",
                "--keep-going",
                "-n",
                "-T",
                "-b",
                "linkcheck",
                "-d",
                str(doctree_dir),
                ".",
                "./_build/linkcheck",
                env=_make_env_vars({"TS_ARQ_MODE": "test"}),
            )
        except CommandFailed:
            output_path = Path("_build") / "linkcheck" / "output.txt"
            if output_path.exists():
                sys.stdout.write(output_path.read_text())
            session.error("Link check reported errors")


@session(name="create-migration", uv_groups=["dev", "lint"])
def create_migration(session: nox.Session) -> None:
    """Create an Alembic migration to the current schema.

    Runs the existing migrations against an empty database to reproduce
    the current released schema, then autogenerates a new migration by
    comparing it to the schema declared in the code. Pass the migration
    message as a positional argument::

        nox -s create-migration -- "Add the widget table."
    """
    message = session.posargs[0] if session.posargs else "Autogenerated"
    with _start_containers() as env_vars:
        env_vars["TS_PATH_PREFIX"] = "/times-square/api"
        session.run("alembic", "upgrade", "head", env=env_vars)
        session.run(
            "alembic",
            "revision",
            "--autogenerate",
            "-m",
            message,
            env=env_vars,
        )


@session(name="run", uv_groups=["dev"])
def run(session: nox.Session) -> None:
    """Run the development server with backing services in containers."""
    with _start_containers() as env_vars:
        env_vars["TS_PATH_PREFIX"] = "/times-square/api"
        session.run("times-square", "init", env=env_vars)
        session.run("times-square", "develop", *session.posargs, env=env_vars)


@session(name="cli", uv_groups=["dev"])
def cli(session: nox.Session) -> None:
    """Run a times-square CLI command against containerized services.

    Pass arguments to the CLI as positional arguments to this session::

        nox -s cli -- --help
    """
    with _start_containers() as env_vars:
        env_vars["TS_PATH_PREFIX"] = "/times-square/api"
        session.run("times-square", *session.posargs, env=env_vars)


@nox.session(name="scriv-create")
def scriv_create(session: nox.Session) -> None:
    """Create a scriv changelog entry."""
    session.install("scriv")
    session.run("scriv", "create")


@nox.session(name="scriv-collect")
def scriv_collect(session: nox.Session) -> None:
    """Collect scriv changelog entries."""
    session.install("scriv")
    session.run("scriv", "collect", "--add", "--version", *session.posargs)


def _setup_testcontainers_logging() -> None:
    """Configure logging to reduce testcontainers noise."""
    logging.getLogger("testcontainers").setLevel(logging.ERROR)
    logging.getLogger("docker").setLevel(logging.ERROR)
    logging.getLogger("urllib3").setLevel(logging.ERROR)


def _setup_testcontainers_env() -> None:
    """Configure testcontainers environment variables for Colima on macOS.

    This must be called before any containers are started to ensure the
    Reaper can connect properly when using Colima as the Docker runtime.
    """
    # Set testcontainers host override for Colima on macOS
    # This fixes "nodename nor servname provided, or not known" errors
    docker_host = os.getenv("DOCKER_HOST", "")
    m = re.search(r"\.colima/(?P<profile>[^/]+)/docker\.sock$", docker_host)
    if m:
        # Extract the Colima VM IP address for the active profile.
        # colima ls -j emits one JSON object per line (one per profile).
        try:
            result = subprocess.run(
                ["colima", "ls", "-j"],
                capture_output=True,
                text=True,
                check=True,
            )
            for line in result.stdout.splitlines():
                if not line.strip():
                    continue
                colima_info = json.loads(line)
                if colima_info.get("name") == m["profile"] and colima_info.get(
                    "address"
                ):
                    os.environ["TESTCONTAINERS_HOST_OVERRIDE"] = colima_info[
                        "address"
                    ]
                    break
        except (
            subprocess.CalledProcessError,
            json.JSONDecodeError,
            KeyError,
        ):
            # If we can't get the Colima address, don't set override
            pass


@contextmanager
def _start_containers() -> Iterator[dict[str, str]]:
    """Start PostgreSQL and Redis containers for a session.

    Yields
    ------
    dict of str
        Environment variables configuring the application to use the
        containerized services.
    """
    _setup_testcontainers_logging()
    _setup_testcontainers_env()

    # Import after setting environment variables so that the testcontainers
    # configuration reads the Colima host override correctly.
    from testcontainers.postgres import PostgresContainer  # noqa: PLC0415
    from testcontainers.redis import RedisContainer  # noqa: PLC0415

    with RedisContainer() as redis:
        redis_host = redis.get_container_host_ip()
        redis_port = redis.get_exposed_port(redis.port)
        redis_url = f"redis://{redis_host}:{redis_port}"

        with PostgresContainer(
            dbname="timessquare", username="timessquare", driver=None
        ) as postgres:
            yield _make_env_vars(
                {
                    "TS_DATABASE_URL": postgres.get_connection_url(),
                    "TS_DATABASE_PASSWORD": postgres.password,
                    "TS_REDIS_URL": f"{redis_url}/0",
                    "TS_REDIS_QUEUE_URL": f"{redis_url}/1",
                }
            )


def _make_env_vars(overrides: dict[str, str] | None = None) -> dict[str, str]:
    """Create an environment variable dictionary for sessions that enables
    the application to start up.
    """
    env_vars = {
        "SAFIR_PROFILE": "development",
        "SAFIR_LOG_LEVEL": "DEBUG",
        "TS_ENVIRONMENT_URL": "https://test.example.com",
        "TS_ENVIRONMENT_NAME": "testing",
        "TS_ALEMBIC_CONFIG_PATH": str(Path(__file__).parent / "alembic.ini"),
        # These placeholder service URLs are overridden with real container
        # URLs by sessions that start containers.
        "TS_DATABASE_URL": "postgresql://timessquare@localhost:5433/timessquare",
        "TS_DATABASE_PASSWORD": "INSECURE-PASSWORD",
        "TS_REDIS_URL": "redis://localhost:6379/0",
        "TS_REDIS_QUEUE_URL": "redis://localhost:6379/1",
        "TS_GAFAELFAWR_TOKEN": _TEST_GAFAELFAWR_TOKEN,
        "TS_ENABLE_GITHUB_APP": "false",
        "TS_GITHUB_APP_PRIVATE_KEY": "foo",
        "TS_GITHUB_WEBHOOK_SECRET": "foo",
    }
    if overrides:
        env_vars.update(overrides)
    return env_vars
